name: "Hello World"
description: "Greet someone and record the time"

inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"

  install-command:
    description: "Install command - optional (e.g. npm install)"
    required: false

  build-command:
    description: "Build command - optional (e.g. npm run build)"
    required: false

  file-list:
    description: "List of files to copy"
    required: false

  GITHUB_TOKEN:
    description: "Github token of the repository (automatically created by Github)"
    default: ${{ github.token }}
    required: false

outputs:
  time: # id of output
    description: "The time we greeted you"
    value: ${{ steps.hello.outputs.time }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 20

    - name: install
      if: ${{ inputs.install-command }}
      run: ${{ inputs.install-command }}
      shell: bash

    - name: build
      if: ${{ inputs.build-command }}
      run: ${{ inputs.build-command }}
      shell: bash

    - name: run action
      id: hello
      run: node ${{ github.action_path }}/dist/index.js "${{ inputs.file-list }}"
      shell: bash

    - name: Comment PR with execution number
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
        comment_tag: execution
