name: "Hello World"
description: "Greet someone and record the time"

inputs:
  install-command:
    description: "Install command - optional (e.g. npm install)"
    required: false

  build-command:
    description: "Build command - optional (e.g. npm run build)"
    required: false

  GITHUB_TOKEN:
    description: "Github token of the repository (automatically created by Github)"
    default: ${{ github.token }}
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"
    value: ${{ steps.hello.outputs.time }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 20

    - name: install
      if: ${{ inputs.install-command }}
      run: ${{ inputs.install-command }}
      shell: bash

    - name: build
      if: ${{ inputs.build-command }}
      run: ${{ inputs.build-command }}
      shell: bash

    - name: run action
      id: hello
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js

    - name: Save output and PR number
      shell: bash
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR
        echo ${{ steps.hello.outputs.time }} > ./pr/${{ github.event.number }}.md

    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
