name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  GITHUB_TOKEN:
    description: "Github token of the repository (automatically created by Github)"
    default: ${{ github.token }}
    required: false
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
